### ISSUE TITLE
nougat-mako-dev: kernel build script outdated

### ISSUE THREAD

**Issue by xsmile** [ganadist/device_lge_occam#3]
The CROSS_COMPILE variable should be updated to reflect the toolchain update.

CROSS_COMPILE="${ANDROID_BUILD_TOP}/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-".

P.S. Thanks for quick update to Nougat.

**Comment by ganadist** [comment]
I'll move script file to https://github.com/ganadist/vendor_fake_nexus/blob/nougat-dev/build/kernel_build
